name: stdprops-tf
channels:
  - conda-forge

dependencies:
  # General
  - python
  - jupyter
  - jupytext
  - tqdm

  # Scientific stack
  - python
  - numpy
  - pandas
  - scikit-learn
  - openpyxl

  # Tensorflow
  - tensorflow 
  - tensorflow-base 
  - tensorflow-cpu  # [linux]
  - tensorflow-estimator 
  - keras

  # Plots
  - plotly
  - seaborn
  - matplotlib
  
  # Extra deps with pip (unfortunately, not recommended)
  - pip
  - pip:
    - kaleido

environment:
  DATAPATH: {{ root }}/data
